### ISSUE TITLE
Fix Friend Activity

### ISSUE THREAD

**Issue by spectrapulse** [harbassan/spicetify-galaxy#8]
Currently the Friend Activity sidebar isn't themed so it has the default black and non-transparent background. 
It would be nice if this could be added and that maybe additionally the heading text could be slightly moved up so it looks less weird.

How it currently looks with the Friend Activity sidebar enabled:  
![](https://cdn.spectrapulse.io/share/2023/01/1672860290.png)

**Comment by spectrapulse** [comment]
> are you using the marketplace version? If not when did you install the theme?

Oh yeah I'm using the marketplace version. Is it out of date?

**Comment by harbassan** [comment]
Nah it should be fine i'm just trying to figure out why its doing that.

**Comment by spectrapulse** [comment]
I'm running: 
```
Spotify for Windows
1.1.96.785.g464c973a
```

**Comment by harbassan** [comment]
should be fixed once it updates on marketplace. Might take a little while.

**Comment by spectrapulse** [comment]
It looks like it has updated (according to "last updated" in the store) but it's still happening weirdly enough. 

![screenshot 1](https://cdn.spectrapulse.io/share/2023/01/1672889206.png)

~~It also might be worth mentioning that the heading text in the store is off~~
![screenshot 2](https://cdn.spectrapulse.io/share/2023/01/1672889308.png)

I've even tried reinstalling Spicetify with Spicetify-EasyInstall but I'm now going to try forcing it to install the latest version of Spotify instead of the recommended version to see if it also happens on that version as well.

Odd.

**Comment by spectrapulse** [comment]
So I've forced it to install the latest Spotify client and it also installed a newer version of Spicetify. It seems to work fine now. Maybe it was caused by the older version of Spicetify.

Currently on:
```
Spicetify 2.16.0
Spotify For Windows 1.2.0
```

I was on:
```
Spicetify 2.14.0 
Spotify for Windows 1.1.96
``` 
Maybe would help others in the future.

**Comment by harbassan** [comment]
Yep, I knew the latest version would work fine I was just trying to get it to work with previous versions in case anyone else had the same issue. About the marketplace header it doesn't have anything to do with the theme its probably a matter of updating marketplace as you said.

**Comment by spectrapulse** [comment]
> Yep, I knew the latest version would work fine I was just trying to get it to work with previous versions in case anyone else had the same issue. About the marketplace header it doesn't have anything to do with the theme its probably a matter of updating marketplace as you said.

I wouldn't say it is exactly fixed. I've updated my marketplace as well and it just looks to be fixed in position which happens to be behind the sidebar for people with the default sidebar size.

![https://cdn.spectrapulse.io/share/2023/01/1672921524.png](https://cdn.spectrapulse.io/share/2023/01/1672921524.png)

**Comment by harbassan** [comment]
Once the theme updates let me know if the heading issue gets fixed.
